In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.metrics import r2_score
df=pd.read_csv('C:\\Users\\Awadhesh\\dataset1\\auto-mpg.csv')

In [2]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198.0,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199.0,97,2774,15.5,70,1,amc hornet
17,21.0,6,200.0,85,2587,16.0,70,1,ford maverick
18,27.0,4,97.0,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104.0,95,2375,17.5,70,2,saab 99e
23,26.0,4,121.0,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199.0,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97.0,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27.0,4,112.0,88,2640,18.6,82,1,chevrolet cavalier wagon
369,34.0,4,112.0,88,2395,18.0,82,1,chevrolet cavalier 2-door
370,31.0,4,112.0,85,2575,16.2,82,1,pontiac j2000 se hatchback
371,29.0,4,135.0,84,2525,16.0,82,1,dodge aries se
372,27.0,4,151.0,90,2735,18.0,82,1,pontiac phoenix
373,24.0,4,140.0,92,2865,16.4,82,1,ford fairmont futura
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl
375,36.0,4,105.0,74,1980,15.3,82,2,volkswagen rabbit l
376,37.0,4,91.0,68,2025,18.2,82,3,mazda glc custom l
377,31.0,4,91.0,68,1970,17.6,82,3,mazda glc custom
378,38.0,4,105.0,63,2125,14.7,82,1,plymouth horizon miser
379,36.0,4,98.0,70,2125,17.3,82,1,mercury lynx l
380,36.0,4,120.0,88,2160,14.5,82,3,nissan stanza xe
381,36.0,4,107.0,75,2205,14.5,82,3,honda accord
382,34.0,4,108.0,70,2245,16.9,82,3,toyota corolla
383,38.0,4,91.0,67,1965,15.0,82,3,honda civic
384,32.0,4,91.0,67,1965,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67,1995,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110,2945,16.4,82,1,buick century limited
387,38.0,6,262.0,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [3]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [4]:
df.shape

(398, 9)

In [5]:
df.isnull()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
368,False,False,False,False,False,False,False,False,False
369,False,False,False,False,False,False,False,False,False
370,False,False,False,False,False,False,False,False,False
371,False,False,False,False,False,False,False,False,False
372,False,False,False,False,False,False,False,False,False
373,False,False,False,False,False,False,False,False,False
374,False,False,False,False,False,False,False,False,False
375,False,False,False,False,False,False,False,False,False
376,False,False,False,False,False,False,False,False,False
377,False,False,False,False,False,False,False,False,False
378,False,False,False,False,False,False,False,False,False
379,False,False,False,False,False,False,False,False,False
380,False,False,False,False,False,False,False,False,False
381,False,False,False,False,False,False,False,False,False
382,False,False,False,False,False,False,False,False,False
383,False,False,False,False,False,False,False,False,False
384,False,False,False,False,False,False,False,False,False
385,False,False,False,False,False,False,False,False,False
386,False,False,False,False,False,False,False,False,False
387,False,False,False,False,False,False,False,False,False
388,False,False,False,False,False,False,False,False,False
389,False,False,False,False,False,False,False,False,False
390,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False

In [6]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [7]:
df = df[df.horsepower != '?']

In [8]:
print('?' in df.horsepower)

False

In [9]:
df=df.drop(['car name'], axis=1)

In [10]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130,3504,12.0,70,1
1,15.0,8,350.0,165,3693,11.5,70,1
2,18.0,8,318.0,150,3436,11.0,70,1
3,16.0,8,304.0,150,3433,12.0,70,1
4,17.0,8,302.0,140,3449,10.5,70,1
5,15.0,8,429.0,198,4341,10.0,70,1
6,14.0,8,454.0,220,4354,9.0,70,1
7,14.0,8,440.0,215,4312,8.5,70,1
8,14.0,8,455.0,225,4425,10.0,70,1
9,15.0,8,390.0,190,3850,8.5,70,1
10,15.0,8,383.0,170,3563,10.0,70,1
11,14.0,8,340.0,160,3609,8.0,70,1
12,15.0,8,400.0,150,3761,9.5,70,1
13,14.0,8,455.0,225,3086,10.0,70,1
14,24.0,4,113.0,95,2372,15.0,70,3
15,22.0,6,198.0,95,2833,15.5,70,1
16,18.0,6,199.0,97,2774,15.5,70,1
17,21.0,6,200.0,85,2587,16.0,70,1
18,27.0,4,97.0,88,2130,14.5,70,3
19,26.0,4,97.0,46,1835,20.5,70,2
20,25.0,4,110.0,87,2672,17.5,70,2
21,24.0,4,107.0,90,2430,14.5,70,2
22,25.0,4,104.0,95,2375,17.5,70,2
23,26.0,4,121.0,113,2234,12.5,70,2
24,21.0,6,199.0,90,2648,15.0,70,1
25,10.0,8,360.0,215,4615,14.0,70,1
26,10.0,8,307.0,200,4376,15.0,70,1
27,11.0,8,318.0,210,4382,13.5,70,1
28,9.0,8,304.0,193,4732,18.5,70,1
29,27.0,4,97.0,88,2130,14.5,71,3
...,...,...,...,...,...,...,...,...
367,28.0,4,112.0,88,2605,19.6,82,1
368,27.0,4,112.0,88,2640,18.6,82,1
369,34.0,4,112.0,88,2395,18.0,82,1
370,31.0,4,112.0,85,2575,16.2,82,1
371,29.0,4,135.0,84,2525,16.0,82,1
372,27.0,4,151.0,90,2735,18.0,82,1
373,24.0,4,140.0,92,2865,16.4,82,1
375,36.0,4,105.0,74,1980,15.3,82,2
376,37.0,4,91.0,68,2025,18.2,82,3
377,31.0,4,91.0,68,1970,17.6,82,3
378,38.0,4,105.0,63,2125,14.7,82,1
379,36.0,4,98.0,70,2125,17.3,82,1
380,36.0,4,120.0,88,2160,14.5,82,3
381,36.0,4,107.0,75,2205,14.5,82,3
382,34.0,4,108.0,70,2245,16.9,82,3
383,38.0,4,91.0,67,1965,15.0,82,3
384,32.0,4,91.0,67,1965,15.7,82,3
385,38.0,4,91.0,67,1995,16.2,82,3
386,25.0,6,181.0,110,2945,16.4,82,1
387,38.0,6,262.0,85,3015,17.0,82,1
388,26.0,4,156.0,92,2585,14.5,82,1
389,22.0,6,232.0,112,2835,14.7,82,1
390,32.0,4,144.0,96,2665,13.9,82,3
391,36.0,4,135.0,84,2370,13.0,82,1
392,27.0,4,151.0,90,2950,17.3,82,1
393,27.0,4,140.0,86,2790,15.6,82,1
394,44.0,4,97.0,52,2130,24.6,82,2
395,32.0,4,135.0,84,2295,11.6,82,1
396,28.0,4,120.0,79,2625,18.6,82,1
397,31.0,4,119.0,82,2720,19.4,82,1

In [11]:
df.horsepower = df.horsepower.astype('float')
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model year        int64
origin            int64
dtype: object

In [12]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,1
1,15.0,8,350.0,165.0,3693,11.5,70,1
2,18.0,8,318.0,150.0,3436,11.0,70,1
3,16.0,8,304.0,150.0,3433,12.0,70,1
4,17.0,8,302.0,140.0,3449,10.5,70,1

In [13]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,23.445918,5.471939,194.411990,104.469388,2977.584184,15.541327,75.979592,1.576531
std,7.805007,1.705783,104.644004,38.491160,849.402560,2.758864,3.683737,0.805518
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.000000,4.000000,105.000000,75.000000,2225.250000,13.775000,73.000000,1.000000
50%,22.750000,4.000000,151.000000,93.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,275.750000,126.000000,3614.750000,17.025000,79.000000,2.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000

In [14]:
df.mpg.describe()

count    392.000000
mean      23.445918
std        7.805007
min        9.000000
25%       17.000000
50%       22.750000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

In [15]:
#sns.distplot(data['mpg'])

In [16]:
#print("Kurtosis: %f" % data['mpg'].kurt())
print("Skewness: %f" % df['mpg'].skew())
df['mpg'].skew()

Skewness: 0.457092

0.45709232306041025

In [17]:
x = df.iloc[:,1:7]

In [18]:
x

     cylinders  displacement  horsepower  weight  acceleration  model year
0            8         307.0       130.0    3504          12.0          70
1            8         350.0       165.0    3693          11.5          70
2            8         318.0       150.0    3436          11.0          70
3            8         304.0       150.0    3433          12.0          70
4            8         302.0       140.0    3449          10.5          70
5            8         429.0       198.0    4341          10.0          70
6            8         454.0       220.0    4354           9.0          70
7            8         440.0       215.0    4312           8.5          70
8            8         455.0       225.0    4425          10.0          70
9            8         390.0       190.0    3850           8.5          70
10           8         383.0       170.0    3563          10.0          70
11           8         340.0       160.0    3609           8.0          70
12           8         400.0       150.0    3761           9.5          70
13           8         455.0       225.0    3086          10.0          70
14           4         113.0        95.0    2372          15.0          70
15           6         198.0        95.0    2833          15.5          70
16           6         199.0        97.0    2774          15.5          70
17           6         200.0        85.0    2587          16.0          70
18           4          97.0        88.0    2130          14.5          70
19           4          97.0        46.0    1835          20.5          70
20           4         110.0        87.0    2672          17.5          70
21           4         107.0        90.0    2430          14.5          70
22           4         104.0        95.0    2375          17.5          70
23           4         121.0       113.0    2234          12.5          70
24           6         199.0        90.0    2648          15.0          70
25           8         360.0       215.0    4615          14.0          70
26           8         307.0       200.0    4376          15.0          70
27           8         318.0       210.0    4382          13.5          70
28           8         304.0       193.0    4732          18.5          70
29           4          97.0        88.0    2130          14.5          71
..         ...           ...         ...     ...           ...         ...
367          4         112.0        88.0    2605          19.6          82
368          4         112.0        88.0    2640          18.6          82
369          4         112.0        88.0    2395          18.0          82
370          4         112.0        85.0    2575          16.2          82
371          4         135.0        84.0    2525          16.0          82
372          4         151.0        90.0    2735          18.0          82
373          4         140.0        92.0    2865          16.4          82
375          4         105.0        74.0    1980          15.3          82
376          4          91.0        68.0    2025          18.2          82
377          4          91.0        68.0    1970          17.6          82
378          4         105.0        63.0    2125          14.7          82
379          4          98.0        70.0    2125          17.3          82
380          4         120.0        88.0    2160          14.5          82
381          4         107.0        75.0    2205          14.5          82
382          4         108.0        70.0    2245          16.9          82
383          4          91.0        67.0    1965          15.0          82
384          4          91.0        67.0    1965          15.7          82
385          4          91.0        67.0    1995          16.2          82
386          6         181.0       110.0    2945          16.4          82
387          6         262.0        85.0    3015          17.0          82
388          4         156.0        92.0    2585          14.5          82
389          6         232.0       112.0    2835          14.7          82
390          4         144.0        96.0    2665          13.9          82
391          4         135.0        84.0    2370          13.0          82
392          4         151.0        90.0    2950          17.3          82
393          4         140.0        86.0    2790          15.6          82
394          4          97.0        52.0    2130          24.6          82
395          4         135.0        84.0    2295          11.6          82
396          4         120.0        79.0    2625          18.6          82
397          4         119.0        82.0    2720          19.4          82

[392 rows x 6 columns]

In [19]:
y=df.iloc[:,0]

In [20]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
5      15.0
6      14.0
7      14.0
8      14.0
9      15.0
10     15.0
11     14.0
12     15.0
13     14.0
14     24.0
15     22.0
16     18.0
17     21.0
18     27.0
19     26.0
20     25.0
21     24.0
22     25.0
23     26.0
24     21.0
25     10.0
26     10.0
27     11.0
28      9.0
29     27.0
       ...
367    28.0
368    27.0
369    34.0
370    31.0
371    29.0
372    27.0
373    24.0
375    36.0
376    37.0
377    31.0
378    38.0
379    36.0
380    36.0
381    36.0
382    34.0
383    38.0
384    32.0
385    38.0
386    25.0
387    38.0
388    26.0
389    22.0
390    32.0
391    36.0
392    27.0
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.33,random_state=324)

In [22]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

In [24]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
lr.score(x_train,y_train)

0.8040296080178922

In [26]:
pred=lr.predict(x_test)

In [27]:
print(pred)

[32.38606195 15.48661935  9.77212223 29.5776586  22.65542583 17.22847868
 12.59863497 16.36921159 25.44854983 10.90935887 18.83947577 35.03616348
 32.47635165 30.53433537 27.17777184 32.67779046 10.77051913  7.45730784
 29.97739643 16.29339526 19.6864682  22.25111073 29.32517273 23.99771998
 13.5761416  25.73425378 20.10853122 15.99372785 23.85860919 19.57030967
 31.5513358  25.08227648 23.13146669 22.09377565 28.58253433 24.29224415
  5.76654664 31.26995076 33.11753473 24.42060599 18.63210481 32.89850531
 16.4748924   8.20338991 20.10638518 26.15294945 25.5490278  16.3030033
 23.39663308 30.86459534  4.43028483 18.23493652  9.82356712 29.09085633
 25.84363006 15.46374669 24.06513949 25.05455927 24.85402476 31.17248527
 32.02904907 26.70884394 23.06230534 27.52533876 33.86932988 21.88748941
 29.83796432 32.33801302 10.68365233 14.24759615 15.054325   20.18372783
 30.43535356  5.54702164 34.20387325 11.43533974 22.24628227 33.03607273
 17.26092374 31.13140645 31.01709282 14.07242568 19.46844306 25.32664757
 27.44254354 19.5831163  31.23098834 20.83084677 33.59256319 16.37884883
 24.66976292 29.59192092 26.38942663 32.26001999  9.29742043 27.43667074
 20.63284294 28.41071603 31.42485775 30.5629159  28.71957323 32.30927311
 32.19306596 30.39695066 33.92149903 21.39879803 14.78000787 25.23316319
 30.92409213  9.4661738  11.15447863 21.55653977 21.29276138 12.20209979
  7.398811   16.70017958  7.91045826 26.49768936 31.22386773 27.29335409
 12.46224871 24.28650592  8.24659364 26.59137513  7.96208438 30.5564238
 13.00257993 23.95236893 30.15390985 34.06608229]

In [28]:
print(y_test)

324    40.8
96     13.0
139    14.0
358    31.6
107    18.0
214    13.0
157    15.0
211    16.5
236    25.5
159    14.0
290    15.5
377    31.0
353    33.0
367    28.0
361    25.4
395    32.0
74     13.0
43     13.0
195    29.0
133    16.0
128    15.0
22     25.0
268    27.2
280    21.5
212    16.5
234    24.5
97     18.0
86     14.0
177    23.0
76     18.0
       ...
205    28.0
322    46.6
331    33.8
266    30.0
379    36.0
101    23.0
188    16.0
61     21.0
388    26.0
8      14.0
138    14.0
166    13.0
263    17.7
116    16.0
103    11.0
208    13.0
104    12.0
148    26.0
302    34.5
147    24.0
75     14.0
60     20.0
26     10.0
141    29.0
95     12.0
279    29.5
9      15.0
171    24.0
197    29.0
329    44.6
Name: mpg, Length: 130, dtype: float64

In [29]:
print("Mean Absolutes Error",mean_absolute_error(y_test,pred))

Mean Absolutes Error 2.7973508969769383

In [30]:
print("Mean Squarr Error",mean_squared_error(y_test,pred))

Mean Squarr Error 13.417414659226525

In [31]:
print(" Root Mean Squarr Error",np.sqrt(mean_squared_error(y_test,pred)))

 Root Mean Squarr Error 3.662978932402768